### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by kensanata** [CurtTilmes/perl6-libgit2#3]
Tagging a release 0.3 would be good because 541207e didn't make it into 0.2 which prevents `zef` from installing this library.

**Comment by CurtTilmes** [comment]
Tagged release 0.3.  Sorry this took so long.  Fell through the cracks in my brain.

zef will probably still fail on some tests -- need a lot of mocking to get all the tests working on arbitrary systems rather than just my box.
